apiVersion: v1
kind: Service
metadata:
  name: case-api-service  
spec:
  selector:
    app: case-api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 31023
  type: NodePort